# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMetadataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text=None, max_length=68)),
                ('description', models.CharField(blank=True, default='', help_text=None, max_length=155)),
                ('keywords', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('heading', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='model')),
            ],
            options={
                'verbose_name': 'my metadata (Model)',
                'verbose_name_plural': 'my metadatas (Model)',
            },
        ),
        migrations.CreateModel(
            name='MyMetadataModelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text=None, max_length=68)),
                ('description', models.CharField(blank=True, default='', help_text=None, max_length=155)),
                ('keywords', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('heading', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('_path', models.CharField(blank=True, editable=False, max_length=255, verbose_name='path')),
                ('_object_id', models.PositiveIntegerField(verbose_name='ID')),
                ('_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='model')),
            ],
            options={
                'verbose_name': 'my metadata (Model Instance)',
                'verbose_name_plural': 'my metadatas (Model Instance)',
            },
        ),
        migrations.CreateModel(
            name='MyMetadataPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text=None, max_length=68)),
                ('description', models.CharField(blank=True, default='', help_text=None, max_length=155)),
                ('keywords', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('heading', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('_path', models.CharField(max_length=255, verbose_name='path')),
            ],
            options={
                'verbose_name': 'my metadata (Path)',
                'verbose_name_plural': 'my metadatas (Path)',
            },
        ),
        migrations.CreateModel(
            name='MyMetadataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text=None, max_length=68)),
                ('description', models.CharField(blank=True, default='', help_text=None, max_length=155)),
                ('keywords', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('heading', models.CharField(blank=True, default='', help_text=None, max_length=511)),
                ('_view', models.CharField(blank=True, default='', max_length=255, verbose_name='view')),
            ],
            options={
                'verbose_name': 'my metadata (View)',
                'verbose_name_plural': 'my metadatas (View)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mymetadataview',
            unique_together=set([('_view',)]),
        ),
        migrations.AlterUniqueTogether(
            name='mymetadatapath',
            unique_together=set([('_path',)]),
        ),
        migrations.AlterUniqueTogether(
            name='mymetadatamodelinstance',
            unique_together=set([('_path',), ('_content_type', '_object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mymetadatamodel',
            unique_together=set([('_content_type',)]),
        ),
    ]
